services :
  # default configuration for services in *this* file
  _defaults :
    autowire : true      # Automatically injects dependencies in your services.
    autoconfigure : true # Automatically registers your services as commands, event subscribers, etc.
    public : false

  Reifinger\ :
    resource : '../src/*'
    exclude : '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

  Reifinger\Infrastructure\GoProAccess\Service\GoProMediaService :
    arguments :
      $goproIp : '%env(GOPRO_IP)%'
      $goproCherokeePort : '%env(GOPRO_CHEROKEE_PORT)%'

  Reifinger\Infrastructure\GoProAccess\Service\GoProControlService :
    arguments :
      $goproIp : '%env(GOPRO_IP)%'

  Symfony\Component\Console\Style\SymfonyStyle :
    arguments :
      $input : '@Symfony\Component\Console\Input\ArgvInput'
      $output : '@Symfony\Component\Console\Output\ConsoleOutput'

  Symfony\Component\Console\Input\ArgvInput :
    public : true

  Symfony\Component\Console\Output\ConsoleOutput :
    public : true
